import uuid
from typing import List, Optional, Literal
from pydantic import BaseModel, Field
from backend.config import settings

class TeamMission(BaseModel):
    team_name: str = Field(description="The name of the contender (e.g., 'Team Python')")
    stance: str = Field(description="A single declarative sentence the team will defend.")
    mission_goal: str = Field(description="What the team must prove to WIN — specific, not vague.")

class ArenaManifestLLM(BaseModel):
    """What the LLM is responsible for generating if the debate is valid."""
    topic: str = Field(description="The high-level subject or user question.")
    team_a: TeamMission
    team_b: TeamMission
    judicial_focus: List[str] = Field(
        description="The rubric the Judge will use to score the debate."
    )

class DispatcherOutput(BaseModel):
    """The master output for the Dispatcher LLM. It chooses to either clarify OR generate a manifest."""
    clarification_needed: bool = Field(
        description="Set to True ONLY if the user's query is too vague, open-ended, or lacks two clear sides (e.g., 'best anime'). Set to False if it's a clear comparison."
    )
    clarification_response: Optional[str] = Field(
        description="If clarification is needed, a brief response telling the user to provide two clear sides.",
        default=None
    )
    manifest: Optional[ArenaManifestLLM] = Field(
        description="If clarification is NOT needed, provide the fully generated debate manifest.",
        default=None
    )

class ArenaManifest(ArenaManifestLLM):
    """Full manifest with system-controlled fields added after LLM generation."""
    session_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    max_rounds: int = Field(default_factory=lambda: settings.MAX_ROUNDS)

class StrategyDocument(BaseModel):
    """Internal strategy generated by the Strategist for the team."""
    win_condition: str = Field(
        description="A concise statement of exactly what the team must prove to win this round based on the Judge's focus."
    )
    core_claims: List[str] = Field(
        description="The 2-3 primary arguments the team will deploy this round."
    )
    anticipated_attacks: List[str] = Field(
        description="2-3 attacks the opponent will likely make, relevant to the judicial focus. Format each as: 'ATTACK: [what opponent will argue] | COUNTER: [how we defeat it]'."
    )
    research_directives: List[str] = Field(
        description="Specific, targeted claims or stats the Researcher needs to go find via Tavily to prove the core_claims."
    )


class EvidenceItem(BaseModel):
    claim: str = Field(description="The specific claim being supported.")
    source_url: Optional[str] = Field(
        description="The URL of the source. None if no source was found."
    )
    raw_snippet: str = Field(
        description="The exact text copied verbatim from the search results for this source. Do NOT paraphrase."
    )
    extracted_fact: str = Field(
        description="Your interpretation of the raw_snippet. Must be grounded in raw_snippet only."
    )


class EvidenceDocument(BaseModel):
    """Compiled research backing the team's strategy."""
    research_summary: str = Field(description="A brief summary of findings.")
    evidence_list: List[EvidenceItem] = Field(description="List of verified claims and their sources.")
    failed_searches: List[str] = Field(description="Directives that yielded no useful results (if any).")


class CriticDecision(BaseModel):
    status: Literal["APPROVED", "REJECTED"] = Field(
        description="APPROVED if evidence is strong enough to proceed. REJECTED if core claims are unsupported or hallucinated."
    )
    reasoning: str = Field(
        description="Specific explanation of why the evidence was approved or rejected."
    )
    weak_points: List[str] = Field(
        description="Claims that are weakly supported even if status is APPROVED. Empty list if none.",
        default_factory=list
    )
    retry_directive: Optional[str] = Field(
        description="If REJECTED, a specific new search query the Researcher should try instead. None if APPROVED.",
        default=None
    )

class SpeakerOutput(BaseModel):
    argument: str = Field(
        description="The final public-facing debate argument. Aggressive, confident, evidence-grounded."
    )
